trigger: none

resources:
  pipelines:
    - pipeline: buildPipeline
      source: Microservices-Build
      trigger: none

pool:
  name: Azure Pipelines

variables:
  buildConfiguration: 'Release'
  projectPath: 'BuildProjectConsoleApp.csproj'

steps:
- script: |
    echo "Using source branch: $(resources.pipeline.buildPipeline.sourceBranch)"
    echo "Using source commit: $(resources.pipeline.buildPipeline.sourceCommit)"
    echo "Using build number: $(resources.pipeline.buildPipeline.runName)"
  displayName: 'Print Selected Build Version'

- task: DownloadPipelineArtifact@2
  displayName: 'Download Console App Artifact'
  inputs:
    buildType: 'specific'
    artifactName: 'console-app'
    project: 'AzureSamples'
    pipeline: '$(resources.pipeline.buildPipeline.pipelineID)'
    runVersion: 'specific'
    runId: '$(resources.pipeline.buildPipeline.runID)'
    patterns: '**/*.zip'
    targetPath: '$(Pipeline.Workspace)/console-app'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Console App Artifact'
  inputs:
    PathtoPublish: '$(Pipeline.Workspace)/console-app'
    ArtifactName: 'console-app'
    publishLocation: 'Container'
    # Optionally, you can set TargetPath if you want to specify a subfolder in the artifact container

- task: DownloadPipelineArtifact@2
  displayName: 'Download Web API Artifact'
  inputs:
    buildType: 'specific'
    artifactName: 'web-api'
    project: 'AzureSamples'
    pipeline: '$(resources.pipeline.buildPipeline.pipelineID)'
    runVersion: 'specific'
    runId: '$(resources.pipeline.buildPipeline.runID)'
    patterns: '**/*.zip'
    targetPath: '$(Pipeline.Workspace)/web-api'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Web API Artifact'
  inputs:
    PathtoPublish: '$(Pipeline.Workspace)/web-api'
    ArtifactName: 'web-api'
    publishLocation: 'Container'