trigger: none

resources:
  pipelines:
    - pipeline: buildPipeline
      source: Microservices-Build
      trigger: none

pool:
  name: Azure Pipelines

variables:
  buildConfiguration: 'Release'
  projectPath: 'BuildProjectConsoleApp.csproj'

steps:
- script: |
    echo "Using source branch: $(resources.pipeline.buildPipeline.sourceBranch)"
    echo "Using source commit: $(resources.pipeline.buildPipeline.sourceCommit)"
    echo "Using build number: $(resources.pipeline.buildPipeline.runName)"
  displayName: 'Print Selected Build Version'

- task: DownloadPipelineArtifact@2
  displayName: 'Download Console App Artifact'
  inputs:
    buildType: 'specific'
    artifactName: 'console-app'
    project: 'AzureSamples'
    pipeline: '$(resources.pipeline.buildPipeline.pipelineID)'
    runVersion: 'specific'
    runId: '$(resources.pipeline.buildPipeline.runID)'
    patterns: '**/*.zip'
    targetPath: '$(Pipeline.Workspace)/console-app'
    
# - task: DownloadPipelineArtifact@2
#   displayName: 'Download Web API Artifact'
#   inputs:
#     buildType: 'specific'
#     artifactName: 'web-api'
#     patterns: '**/*.zip'
#     targetPath: '$(Pipeline.Workspace)/web-api'

# Example step to do something with the artifacts
- script: |
    echo "Console App files:"
    ls $(Pipeline.Workspace)/console-app
    echo "Web API files:"
    ls $(Pipeline.Workspace)/web-api
  displayName: 'List downloaded artifact contents'