parameters:
  - name: buildVersion
    displayName: 'Build Version to Download'
    type: string
    default: ''
    
trigger: none

resources:
  pipelines:
    - pipeline: buildPipeline
      source: Microservices-Build
      trigger: none

pool:
  name: Azure Pipelines

variables:
  buildConfiguration: 'Release'
  projectPath: 'BuildProjectConsoleApp.csproj'

steps:
- script: |
    echo "Using build version: ${{ parameters.buildVersion }}"
  displayName: 'Print Selected Build Version'

- task: DownloadPipelineArtifact@2
  displayName: 'Download Console App Artifact'
  inputs:
    source: 'specific'
    project: '$(System.TeamProject)'
    pipeline: $(resources.pipelines.buildPipeline.pipelineId)
    runVersion: 'specific'
    runId: '${{ parameters.buildVersion }}'
    artifact: 'console-app'
    path: '$(Pipeline.Workspace)/console-app'
    
- task: DownloadPipelineArtifact@2
  displayName: 'Download Web API Artifact'
  inputs:
    source: 'specific'
    project: '$(System.TeamProject)'
    pipeline: $(resources.pipelines.buildPipeline.pipelineId)
    runVersion: 'specific'
    runId: '${{ parameters.buildVersion }}'
    artifact: 'web-api'
    path: '$(Pipeline.Workspace)/web-api'

# Example step to do something with the artifacts
- script: |
    echo "Console App files:"
    ls $(Pipeline.Workspace)/console-app
    echo "Web API files:"
    ls $(Pipeline.Workspace)/web-api
  displayName: 'List downloaded artifact contents'