parameters:
  - name: buildVersion
    displayName: 'Build Version to Download'
    type: string
    default: ''
    required: true
    
# Set trigger to none to ensure this pipeline is only run manually
trigger: none

resources:
  pipelines:
    - pipeline: buildPipeline
      source: azure-pipelines-build
      trigger: none
      version: ${{ parameters.buildVersion }}

pool:
  name: Azure Pipelines

variables:
  buildConfiguration: 'Release'
  projectPath: 'BuildProjectConsoleApp.csproj'

steps:
- script: |
    echo "Using build version: ${{ parameters.buildVersion }}"
  displayName: 'Print Selected Build Version'

- task: DownloadBuildArtifacts@1
  displayName: 'Download Console App Artifact'
  inputs:
    buildType: 'specific'
    project: '$(System.TeamProject)'
    pipeline: $(resources.pipeline.buildPipeline.pipelineName)
    buildVersionToDownload: 'specific'
    downloadType: 'single'
    artifactName: 'console-app'
    downloadPath: '$(Pipeline.Workspace)'
    buildId: '${{ parameters.buildVersion }}'
    
- task: DownloadBuildArtifacts@1
  displayName: 'Download Web API Artifact'
  inputs:
    buildType: 'specific'
    project: '$(System.TeamProject)'
    pipeline: $(resources.pipeline.buildPipeline.pipelineName)
    buildVersionToDownload: 'specific'
    downloadType: 'single'
    artifactName: 'web-api'
    downloadPath: '$(Pipeline.Workspace)'
    buildId: '${{ parameters.buildVersion }}'

# Example step to do something with the artifacts
- script: |
    echo "Console App files:"
    ls $(Pipeline.Workspace)/console-app
    echo "Web API files:"
    ls $(Pipeline.Workspace)/web-api
  displayName: 'List downloaded artifact contents'