trigger:
  branches:
    include:
    - main
    - master
  paths:
    include:
    - '**'

pool:
  name: Azure Pipelines

variables:
  buildConfiguration: 'Release'
  projectPath: 'BuildProjectConsoleApp.csproj'
  # Set the build number to include a version tag (should match build pipeline)
  name: '$(Build.SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)'

resources:
  pipelines:
    - pipeline: buildPipeline
      source: azure-pipelines-build
      trigger: false
      # Set the version/tag to download artifacts from
      # Replace the value below with the desired build number or set it as a parameter
      run: $(buildVersion)

parameters:
  - name: buildVersion
    displayName: 'Build Version to Download'
    type: string
    default: ''

steps:
- task: DownloadPipelineArtifact@2
  displayName: 'Download Console App Artifact'
  inputs:
    buildType: 'specific'
    project: '$(System.TeamProject)'
    pipeline: $(resources.pipeline.buildPipeline.pipelineId)
    runVersion: 'specific'
    runId: $(resources.pipeline.buildPipeline.runId)
    artifact: 'console-app'
    path: '$(Pipeline.Workspace)/console-app'

- task: DownloadPipelineArtifact@2
  displayName: 'Download Web API Artifact'
  inputs:
    buildType: 'specific'
    project: '$(System.TeamProject)'
    pipeline: $(resources.pipeline.buildPipeline.pipelineId)
    runVersion: 'specific'
    runId: $(resources.pipeline.buildPipeline.runId)
    artifact: 'web-api'
    path: '$(Pipeline.Workspace)/web-api'

# Example step to do something with the artifacts
- script: |
    echo "Console App files:"
    ls $(Pipeline.Workspace)/console-app
    echo "Web API files:"
    ls $(Pipeline.Workspace)/web-api
  displayName: 'List downloaded artifact contents'