trigger:
  branches:
    include:
    - main
    - master
  paths:
    include:
    - '**'

pool:
  name: Azure Pipelines

variables:
  buildConfiguration: 'Release'
  projectPath: 'BuildProjectConsoleApp.csproj'

steps:
- task: DownloadPipelineArtifact@2
  displayName: 'Download Console App Artifact'
  inputs:
    artifact: 'console-app'
    path: '$(Pipeline.Workspace)/console-app'

- task: DownloadPipelineArtifact@2
  displayName: 'Download Web API Artifact'
  inputs:
    artifact: 'web-api'
    path: '$(Pipeline.Workspace)/web-api'

- script: |
    echo "Console App files:"
    ls $(Pipeline.Workspace)/console-app
    echo "Web API files:"
    ls $(Pipeline.Workspace)/web-api
  displayName: 'List downloaded artifact contents'