trigger:
  branches:
    include:
    - main
    - master
  paths:
    include:
    - '**'

pool:
  name: Azure Pipelines

variables:
  buildConfiguration: 'Release'
  consoleAppProjectPath: 'console-apps/BuildProjectConsoleApp/BuildProjectConsoleApp.csproj'
  webApiProjectPath: 'apis/BuildProjectWebApi/BuildProjectWebApi.csproj'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK 8.0'
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages (Console App)'
  inputs:
    command: 'restore'
    projects: '$(consoleAppProjectPath)'

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages (Web API)'
  inputs:
    command: 'restore'
    projects: '$(webApiProjectPath)'

- task: DotNetCoreCLI@2
  displayName: 'Build Console App'
  inputs:
    command: 'build'
    projects: '$(consoleAppProjectPath)'
    arguments: '--configuration $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Build Web API'
  inputs:
    command: 'build'
    projects: '$(webApiProjectPath)'
    arguments: '--configuration $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Publish Console App'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(consoleAppProjectPath)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/console-app'
    zipAfterPublish: false

- task: DotNetCoreCLI@2
  displayName: 'Publish Web API'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(webApiProjectPath)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/web-api'
    zipAfterPublish: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Console App Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/console-app'
    ArtifactName: 'console-app'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Web API Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/web-api'
    ArtifactName: 'web-api'
    publishLocation: 'Container'