parameters:
  - name: buildVersion
    displayName: 'Build Version to Download'
    type: string
    default: ''
    required: true

resources:
  pipelines:
    - pipeline: buildPipeline
      source: azure-pipelines-build
      trigger: false
      # The version will be supplied by the parameter
      version: ${{ parameters.buildVersion }}

trigger:
  branches:
    include:
    - main
    - master
  paths:
    include:
    - '**'

pool:
  name: Azure Pipelines

variables:
  buildConfiguration: 'Release'
  projectPath: 'BuildProjectConsoleApp.csproj'

steps:
- task: DownloadPipelineArtifact@2
  displayName: 'Download Console App Artifact'
  inputs:
    buildType: 'specific'
    project: '$(System.TeamProject)'
    pipeline: $(resources.pipeline.buildPipeline.pipelineId)
    runVersion: 'specific'
    runId: $(resources.pipeline.buildPipeline.runId)
    artifact: 'console-app'
    path: '$(Pipeline.Workspace)/console-app'

- task: DownloadPipelineArtifact@2
  displayName: 'Download Web API Artifact'
  inputs:
    buildType: 'specific'
    project: '$(System.TeamProject)'
    pipeline: $(resources.pipeline.buildPipeline.pipelineId)
    runVersion: 'specific'
    runId: $(resources.pipeline.buildPipeline.runId)
    artifact: 'web-api'
    path: '$(Pipeline.Workspace)/web-api'

# Example step to do something with the artifacts
- script: |
    echo "Console App files:"
    ls $(Pipeline.Workspace)/console-app
    echo "Web API files:"
    ls $(Pipeline.Workspace)/web-api
  displayName: 'List downloaded artifact contents'